#!/bin/bash

echo "======================================"
echo "===== LCD Screen driver installer ===="
echo "======= Created by Aaron Dewes ======="
echo "=== Based on a script by @goodtft ===="
echo "======================================"

#echo "Creating a system backup"
#sudo ./system_backup.sh

if [ -f /etc/X11/xorg.conf.d/40-libinput.conf ]; then
    echo "Deleting old config"
    sudo rm -rf /etc/X11/xorg.conf.d/40-libinput.conf
fi
if [ ! -d /etc/X11/xorg.conf.d ]; then
    echo "Creating configuration directory"
    sudo mkdir -p /etc/X11/xorg.conf.d
fi

echo "Installing kernel overlays"
sudo cp ./usr/tft35a-overlay.dtb /boot/overlays/
sudo cp ./usr/tft35a-overlay.dtb /boot/overlays/tft35a.dtbo

echo "Backing up config.txt"
sudo cp ./boot/config.txt ./boot/config.txt.bak

echo "Adding kernel overlays to boot config"
sudo echo "dtparam=i2c_arm=on" >> ./boot/config.txt
sudo echo "dtparam=spi=on" >> ./boot/config.txt
sudo echo "enable_uart=1" >> ./boot/config.txt
sudo echo "dtoverlay=tft35a:rotate=90" >> ./boot/config.txt

echo "Adding custom X11 config"
sudo cp -rf ./usr/99-calibration.conf-35-90  /etc/X11/xorg.conf.d/99-calibration.conf
sudo cp -rf ./usr/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/99-fbturbo.conf


echo "Installing xserver-xorg-input-evdev"
sudo apt-get install xserver-xorg-input-evdev -y
sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf

sudo sync
sudo sync
sleep 1

echo "======================================"
echo "======= Installation finished ========"
echo "======================================"
echo "== Your Pi will reboot in 5 seconds =="
echo "== Thank you for using this script! =="
echo "======================================"
sleep 5
sudo reboot
